import type { Readable } from 'node:stream';
import type { DataStore } from '@tus/utils';

export class StorageLimitError extends Error {
  constructor(public readonly maxBytes: number) {
    super(`upload exceeds ${maxBytes} bytes`);
    this.name = 'StorageLimitError';
  }
}

export class StorageNotFoundError extends Error {
  constructor(key: string) {
    super(`object not found: ${key}`);
    this.name = 'StorageNotFoundError';
  }
}

export interface PutResult {
  size: number;
  sha256: string;
}

export interface OrphanCleanupOptions {
  /** Only artefacts older than this are touched. */
  olderThanMs: number;
  /** Returns true when the key belongs to a file the database still cares about. */
  isLive: (key: string) => boolean;
}

/**
 * Minimal storage abstraction. Keys are opaque identifiers generated by the
 * application (never derived from client-supplied names) and validated by
 * every backend before touching the filesystem/bucket.
 *
 * The tus DataStore created by `createTusStore()` writes to the same location
 * using the same keys, so a completed tus upload is readable via `get(key)`.
 */
export interface StorageBackend {
  readonly kind: 'local' | 's3';
  /** Streams `source` into a new object. Never buffers the whole payload. Partial data is removed on error. */
  put(key: string, source: Readable, opts: { maxBytes: number }): Promise<PutResult>;
  /** Opens a read stream. Throws StorageNotFoundError. */
  get(key: string): Promise<Readable>;
  stat(key: string): Promise<{ size: number } | null>;
  /** Idempotent. */
  delete(key: string): Promise<void>;
  createTusStore(opts: { expirationMs: number }): DataStore;
  /** Removes the tus bookkeeping object left next to a completed upload. */
  removeTusSidecar(key: string): Promise<void>;
  /** Removes stale partial uploads and bookkeeping objects the database no longer references. */
  cleanupOrphans(opts: OrphanCleanupOptions): Promise<{ removed: number }>;
  /** Cheap readiness probe (directory writable / bucket reachable). */
  healthCheck(): Promise<void>;
}

const KEY_RE = /^[A-Za-z0-9_-]{1,128}$/;

export function assertValidKey(key: string): void {
  if (!KEY_RE.test(key)) throw new Error(`invalid storage key`);
}
